services:
  - type: web
    name: premier-league-betting
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x build.sh && ./build.sh
    envVars:
      - key: ODDS_API_KEY
        sync: false
        value: 9bc157f3e9720cc01a71655708f5c3ca
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONIOENCODING
        value: utf-8
